### ISSUE TITLE
Incorrect `qs dev` behaviour on issue from a different repo in the clipboard

### ISSUE THREAD

**Issue by host6** [untillpro/qs#24]
in the local `upstreammain` branch, tracked branch is https://github.com/untillpro/airs-bp3/tree/main, have `https://github.com/voedger/voedger/issues/53` in the clipboard:
```
$ qs dev
Dev branch 'https-github-comvoedgervoedgerissues53' will be created. Continue(y/n)? 
```
```
$ qs dev https://github.com/voedger/voedger/issues/53
Dev branch 'https-github-comvoedgervoedgerissues53' will be created. Continue(y/n)? 
```
I'm expecting  `53-deactivate-workspace` branch name is suggested +the branch is mentioned at `https://github.com/voedger/voedger/issues/53`

**Comment by ivvist** [comment]
Fixed, Version v1.40.0
