### ISSUE TITLE
qs dev problem on mac os 

### ISSUE THREAD

**Issue by anurmanov** [untillpro/qs#38]
Creating git branch via qs dev command causes creating files .DS_Store. 
<img width="1033" alt="Screenshot 2023-07-12 at 14 54 19" src="https://github.com/untillpro/qs/assets/38488987/b72d49a2-6ee5-403a-8384-7196c63364ff">

**Comment by ivvist** [comment]
A good solution is to add .DS_Store in .gitignore file.

**Comment by host6** [comment]
not actual anymore
