### ISSUE TITLE
problems with `qs pr` for bp3 if created from task in Kaiser

### ISSUE THREAD

**Issue by host6** [untillpro/qs#53]
`qs pr` in the branch created when the follwing was in the clipboard:
```
Strange error in backoffice
https://dev.untill.com/projects/#!685392
```
causes pr with follwing problems:
- name `Strange error in backoffice https://dev.untill.com/projects/#!685392 #976`
  - should be `Strange error in backoffice` ???
  - see https://github.com/untillpro/airs-bp3/pull/976
- press `Squash and merge` button (because building does not start automatically)
  - `Strange error in backofficehttps://dev.untill.com/projects/#!685392 (#976)` (no space!) commit message is suggested
    - should be `Strange error in backoffice (#976)` ???
  - details below the suggested commit message contains all commit messages from my branch like `go on`, `misc` etc
    - should be:
```
Strange error in backoffice
https://dev.untill.com/projects/#!685392
```
or just:
```
https://dev.untill.com/projects/#!685392
```

**Comment by ivvist** [comment]
Fixed here
https://github.com/untillpro/qs/releases/tag/v1.53.0
