### ISSUE TITLE
problems with qs pr for bp3 if created from github issue

### ISSUE THREAD

**Issue by host6** [untillpro/qs#54]
https://github.com/voedger/voedger/issues/1793 is in clipboard, `qs dev` in airs-bp3 repo, `qs pr` -> created pull request https://github.com/untillpro/airs-bp3/pull/977. It contains a comment `Resolves #1793 bp3: refactor restaurant intense usage test (code looks bad)`. Should be: `Resolves https://github.com/voedger/voedger/issues/1793 bp3: refactor restaurant intense usage test (code looks bad)`

**Comment by ivvist** [comment]
It should not contain full URL.
#1793 is a hyperlink - user alwasy can click it and go to the issue.
That was the requirement
